### ISSUE TITLE
Nav bar issue.

### ISSUE THREAD

**Issue by ujjwalkumar1212** [ujjwalkumar1212/Codeword-Generator-Scrutinizer#3]
Navigation bar should not be displayed in the login/Registration/Forgot password page even when all the functionalities are disabled.

**Comment by Naveenkumar-Nuggu** [comment]
Issue has been solved. If we need the nav bar to be shown in any of the page we need to have the following code tags" <app-nav-bar></app-nav-bar>" in that particular page. Make sure that we have to use this tags in the html file of that component
